### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 5.1 για επιτραπέζιους υπολογιστές Windows
  description: Η εφαρμογή Virtualization Hosting 5.1 της Microsoft για επιτραπέζιους υπολογιστές των Windows ακολουθεί την Πολιτική Σταθερού Κύκλου Ζωής.
  ms.date: 09/10/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 9296a136a0bc0da5a6d6b6b8b49d012170158da0
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: el-GR
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1000575"
name: Microsoft Application Virtualization Hosting 5.1 για επιτραπέζιους υπολογιστές Windows
summary: >+
  Η εφαρμογή Virtualization Hosting 5.1 της Microsoft για επιτραπέζιους υπολογιστές των Windows ακολουθεί την Πολιτική [Σταθερού](/lifecycle/policies/fixed) Κύκλου Ζωής.


  Αυτό ισχύει για τις ακόλουθες εκδόσεις: για τους Επιτραπέζιους Υπολογιστές των Windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2015
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Original Release
  startDate: 11/01/2015
  endDate: 04/14/2026
content: "\n## <a name=\"links\"></a>Συνδέσεις \n* [Πληροφορίες Προϊόντος](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n\n\n## <a name=\"editions\"></a>Εκδόσεις \n* Για επιτραπέζιους υπολογιστές Windows"
