### YamlMime:Lifecycle
metadata:
  title: Εικονική διαμόρφωση εφαρμογών της Microsoft 4.6
  description: Η εικονική διαμόρφωση εφαρμογών της Microsoft 4.6 ακολουθεί την πολιτική σταθερού κύκλου ζωής.
  ms.date: 07/28/2020
  ms.openlocfilehash: 868274b4468e663afe8e1b9f36069490ab4da025
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: el-GR
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "818646"
name: Εικονική διαμόρφωση εφαρμογών της Microsoft 4.6
summary: >+
  Η εικονική διαμόρφωση εφαρμογών της Microsoft 4.6 ακολουθεί την [πολιτική σταθερού](/lifecycle/policies/fixed) κύκλου ζωής.


  Αυτό ισχύει για τις ακόλουθες εκδόσεις: για υπηρεσίες απομακρυσμένης επιφάνειας εργασίας, για επιφάνειες εργασίας των Windows, Sequencer

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Συνδέσεις \n* [Πληροφορίες προϊόντος και μετεγκατάστασης](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Οδηγίες για τη μετανάστευση](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Πολιτική service pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Δεδομένου ότι ο υπολογιστής-πελάτης App-V 4.6 χρησιμοποιεί τον διακομιστή App-V 4.5, ο διακομιστής App-V 4.5 θα συνεχίσει να υποστηρίζεται σύμφωνα με τις ημερομηνίες κύκλου ζωής του App-V 4.6 όταν χρησιμοποιείται με τον υποστηριζόμενο υπολογιστή-πελάτη App-V 4.6.\n\n## <a name=\"editions\"></a>Εκδόσεις \n* για υπηρεσίες απομακρυσμένης επιφάνειας εργασίας\n* για επιφάνειες εργασίας των Windows\n* Sequencer"
