### YamlMime:Lifecycle
metadata:
  title: Πύλη εφαρμογών ευφυών επικοινωνιών φαλαινών
  description: Η πύλη εφαρμογής Intelligent Communications Communications ακολουθεί την πολιτική σταθερού κύκλου ζωής.
  ms.date: 08/21/2020
  ms.openlocfilehash: 4946cfbd0c53706853138bd707157a5c318b8dc6
  ms.sourcegitcommit: bc7fcda30191f92db77ed2e7f74d5816ac276a55
  ms.translationtype: MT
  ms.contentlocale: el-GR
  ms.lasthandoff: 08/21/2020
  ms.locfileid: "907140"
name: Πύλη εφαρμογών ευφυών επικοινωνιών φαλαινών
summary: >+
  Η πύλη εφαρμογής Intelligent Communications Communications ακολουθεί την πολιτική [σταθερού](/lifecycle/policies/fixed) κύκλου ζωής.


products:
- windows
policyType: fixed-mainstream-only
supportDates:
  start: 10/10/2007
  end: 07/13/2010
releases:
- version: "3.1"
  startDate: 10/10/2007
  endDate: 07/08/2008
- version: "3.6"
  startDate: 10/10/2007
  endDate: 07/13/2010
content: "\n\n> [!NOTE]\n> Η υποστήριξη για αυτό το προϊόν υπόκειται στους όρους απόκτησής του."
